# Generated by Django 6.0 on 2025-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('picture_url', models.URLField(blank=True, default='https://www.cntraveller.in/story/6-new-restaurants-to-try-in-bengaluru/', null=True)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
